#!/usr/bin/env bash
# lib/events.sh — typed NDJSON event emitters for twincut.
#
# Schema authority: ui/server/events.go Go structs. Every helper here has
# matching field slots; a round-trip test in events_roundtrip_test.go
# decodes the fixtures generated by tests/events_contract.sh and fails on
# drift.
#
# Convention: helpers accept --key value long-options only. Unknown args
# are fatal (return 2). Test seams:
#   TWINCUT_TEST_TS  — override the ts field
#   RUN_ID           — provides run_id (existing global)

# JSON string escaper. Handles backslash, quote, control chars, newline, tab,
# carriage return. Output is bare (no surrounding quotes) so callers can
# compose object literals.
json_escape(){
  local s="${1-}"
  # Named escapes first (backslash must come before others to avoid doubling).
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  s="${s//$'\n'/\\n}"
  s="${s//$'\r'/\\r}"
  s="${s//$'\t'/\\t}"
  s="${s//$'\b'/\\b}"
  s="${s//$'\f'/\\f}"
  # Sweep remaining control characters U+0001..U+001F (excluding the 6 named
  # above: \n=0x0a \r=0x0d \t=0x09 \b=0x08 \f=0x0c) plus U+007F (DEL).
  # Uses bash's POSIX ordinal idiom: printf '%d' "'$char" gives the code point.
  local ctrl hex
  for ctrl in $'\x01' $'\x02' $'\x03' $'\x04' $'\x05' $'\x06' $'\x07' \
              $'\x0b' $'\x0e' $'\x0f' \
              $'\x10' $'\x11' $'\x12' $'\x13' $'\x14' $'\x15' $'\x16' $'\x17' \
              $'\x18' $'\x19' $'\x1a' $'\x1b' $'\x1c' $'\x1d' $'\x1e' $'\x1f' \
              $'\x7f'; do
    if [[ "$s" == *"$ctrl"* ]]; then
      printf -v hex '\\u%04x' "'$ctrl"
      s="${s//$ctrl/$hex}"
    fi
  done
  printf '%s' "$s"
}

# Resolve a timestamp; honor TWINCUT_TEST_TS for fixture-stable output.
_emit_now_ts(){
  if [[ -n "${TWINCUT_TEST_TS:-}" ]]; then
    printf '%s' "$TWINCUT_TEST_TS"
  else
    date -u +%s
  fi
}

# Write a single NDJSON line: fd 3 if open, else stdout.
_emit_write(){
  if { true >&3; } 2>/dev/null; then
    printf '%s\n' "$1" >&3
  else
    printf '%s\n' "$1"
  fi
}

# Validate a numeric field; echo it on stdout if valid, else 0 + warning.
_emit_num(){
  local name="$1" v="$2"
  if [[ "$v" =~ ^-?[0-9]+$ ]]; then
    printf '%s' "$v"
  else
    echo "emit: field $name expected int, got '$v' — using 0" >&2
    printf '0'
  fi
}

# emit_run_start — start-of-run event.
#   --mode VAL      mode string (e.g. thumbnail_detect_preview, thumbnail_detect_apply)
#   --source VAL    source directory absolute path
#   --run-id VAL    optional explicit run_id (overrides $RUN_ID)
emit_run_start(){
  $JSON_EVENTS || return 0
  local mode="" source="" run_id=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --mode)    mode="$2";    shift 2 ;;
      --source)  source="$2";  shift 2 ;;
      --run-id)  run_id="$2";  shift 2 ;;
      *) echo "emit_run_start: unknown arg $1" >&2; return 0 ;;
    esac
  done
  [[ -z "$run_id" ]] && run_id="${RUN_ID:-}"
  local ts; ts=$(_emit_now_ts)
  local out='{"type":"run_start","ts":'"$ts"
  [[ -n "$run_id" ]] && out+=',"run_id":"'"$(json_escape "$run_id")"'"'
  out+=',"mode":"'"$(json_escape "$mode")"'"'
  out+=',"source":"'"$(json_escape "$source")"'"'
  out+='}'
  _emit_write "$out"
}

# emit_run_end — terminal event for a run.
#   --status VAL         one of: succeeded | failed | interrupted
#   --duration-ms INT    optional total run duration
#   --total INT          optional candidate count (apply: total commands seen)
#   --applied INT        optional apply success count
#   --skipped INT        optional apply skip count
emit_run_end(){
  $JSON_EVENTS || return 0
  local status="" duration_ms="" total="" applied="" skipped="" run_id=""
  local restored="" missing="" unrecoverable="" errors=""
  local moved="" deleted="" manifest_path="" cancelled=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --status)          status="$2"; shift 2 ;;
      --duration-ms)     duration_ms="$2"; shift 2 ;;
      --total)           total="$2"; shift 2 ;;
      --applied)         applied="$2"; shift 2 ;;
      --skipped)         skipped="$2"; shift 2 ;;
      --run-id)          run_id="$2"; shift 2 ;;
      --restored)        restored="$2"; shift 2 ;;
      --missing)         missing="$2"; shift 2 ;;
      --unrecoverable)   unrecoverable="$2"; shift 2 ;;
      --errors)          errors="$2"; shift 2 ;;
      --moved)           moved="$2"; shift 2 ;;
      --deleted)         deleted="$2"; shift 2 ;;
      --manifest-path)   manifest_path="$2"; shift 2 ;;
      --cancelled)       cancelled="$2"; shift 2 ;;
      *) echo "emit_run_end: unknown arg $1" >&2; return 0 ;;
    esac
  done
  [[ -z "$run_id" ]] && run_id="${RUN_ID:-}"
  local ts; ts=$(_emit_now_ts)
  local out='{"type":"run_end","ts":'"$ts"
  [[ -n "$run_id" ]] && out+=',"run_id":"'"$(json_escape "$run_id")"'"'
  out+=',"status":"'"$(json_escape "$status")"'"'
  [[ -n "$duration_ms" ]] && out+=',"duration_ms":'"$(_emit_num duration_ms "$duration_ms")"
  [[ -n "$total" ]]       && out+=',"total":'"$(_emit_num total "$total")"
  [[ -n "$applied" ]]     && out+=',"applied":'"$(_emit_num applied "$applied")"
  [[ -n "$skipped" ]]        && out+=',"skipped":'"$(_emit_num skipped "$skipped")"
  [[ -n "$restored" ]]       && out+=',"restored":'"$(_emit_num restored "$restored")"
  [[ -n "$missing" ]]        && out+=',"missing":'"$(_emit_num missing "$missing")"
  [[ -n "$unrecoverable" ]]  && out+=',"unrecoverable":'"$(_emit_num unrecoverable "$unrecoverable")"
  [[ -n "$errors" ]]         && out+=',"errors":'"$(_emit_num errors "$errors")"
  [[ -n "$moved" ]]          && out+=',"moved":'"$(_emit_num moved "$moved")"
  [[ -n "$deleted" ]]        && out+=',"deleted":'"$(_emit_num deleted "$deleted")"
  [[ -n "$manifest_path" ]]  && out+=',"manifest_path":"'"$(json_escape "$manifest_path")"'"'
  case "$cancelled" in
    true|false) out+=',"cancelled":'"$cancelled" ;;
    "") ;;
    *) echo "emit_run_end: --cancelled must be true|false" >&2 ;;
  esac
  out+='}'
  _emit_write "$out"
}

# emit_warn — non-fatal warning event.
#   --code VAL    enum (io_error | missing_file | bad_video | appledouble | ...)
#   --path VAL    optional path the warning is about
#   --detail VAL  free-text human-readable explanation
emit_warn(){
  $JSON_EVENTS || return 0
  local code="" path="" detail="" run_id=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --code)    code="$2"; shift 2 ;;
      --path)    path="$2"; shift 2 ;;
      --detail)  detail="$2"; shift 2 ;;
      --run-id)  run_id="$2"; shift 2 ;;
      *) echo "emit_warn: unknown arg $1" >&2; return 0 ;;
    esac
  done
  [[ -z "$run_id" ]] && run_id="${RUN_ID:-}"
  local ts; ts=$(_emit_now_ts)
  local out='{"type":"warn","ts":'"$ts"
  [[ -n "$run_id" ]] && out+=',"run_id":"'"$(json_escape "$run_id")"'"'
  out+=',"code":"'"$(json_escape "$code")"'"'
  [[ -n "$path" ]]   && out+=',"path":"'"$(json_escape "$path")"'"'
  [[ -n "$detail" ]] && out+=',"detail":"'"$(json_escape "$detail")"'"'
  out+='}'
  _emit_write "$out"
}

# emit_error — fatal-ish error event (run may still continue, but the
# specific operation failed).
#   --code VAL    enum (usage_error | runtime_error | apply_failed | mv_failed | ...)
#   --path VAL    optional path the error is about
#   --detail VAL  free-text
emit_error(){
  $JSON_EVENTS || return 0
  local code="" path="" detail="" run_id=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --code)    code="$2"; shift 2 ;;
      --path)    path="$2"; shift 2 ;;
      --detail)  detail="$2"; shift 2 ;;
      --run-id)  run_id="$2"; shift 2 ;;
      *) echo "emit_error: unknown arg $1" >&2; return 0 ;;
    esac
  done
  [[ -z "$run_id" ]] && run_id="${RUN_ID:-}"
  local ts; ts=$(_emit_now_ts)
  local out='{"type":"error","ts":'"$ts"
  [[ -n "$run_id" ]] && out+=',"run_id":"'"$(json_escape "$run_id")"'"'
  out+=',"code":"'"$(json_escape "$code")"'"'
  [[ -n "$path" ]]   && out+=',"path":"'"$(json_escape "$path")"'"'
  [[ -n "$detail" ]] && out+=',"detail":"'"$(json_escape "$detail")"'"'
  out+='}'
  _emit_write "$out"
}

# emit_thumb_candidate — one event per thumbnail candidate file.
#   --decision VAL        required; one of: thumb_l1_review | thumb_l2_exif | thumb_l3_embed | thumb_confirmed | keep_user_override
#   --path VAL            required; absolute path of the candidate thumbnail
#   --keeper VAL          optional; absolute path of the file being kept
#   --group-id VAL        optional; group identifier (EXIF SHA1, "l3:<sha1>", "l1ph:<sha1>")
#   --width INT           optional; pixel width
#   --height INT          optional; pixel height
#   --size-bytes INT      optional; file size in bytes
#   --phash-distance INT  optional; Hamming distance (L1 matched only)
#   --reason VAL          optional; free-text reason code
#   --run-id VAL          optional; explicit run_id override
emit_thumb_candidate(){
  $JSON_EVENTS || return 0
  local decision="" path="" keeper="" group_id="" width="" height="" size_bytes="" phash_distance="" reason="" run_id=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --decision)        decision="$2"; shift 2 ;;
      --path)            path="$2"; shift 2 ;;
      --keeper)          keeper="$2"; shift 2 ;;
      --group-id)        group_id="$2"; shift 2 ;;
      --width)           width="$2"; shift 2 ;;
      --height)          height="$2"; shift 2 ;;
      --size-bytes)      size_bytes="$2"; shift 2 ;;
      --phash-distance)  phash_distance="$2"; shift 2 ;;
      --reason)          reason="$2"; shift 2 ;;
      --run-id)          run_id="$2"; shift 2 ;;
      *) echo "emit_thumb_candidate: unknown arg $1" >&2; return 0 ;;
    esac
  done
  [[ -z "$run_id" ]] && run_id="${RUN_ID:-}"
  # Validate decision (warn only — do not abort).
  case "$decision" in
    thumb_l1_review|thumb_l2_exif|thumb_l3_embed|thumb_confirmed|keep_user_override) ;;
    *) echo "emit_thumb_candidate: unexpected decision value '$decision'" >&2 ;;
  esac
  local ts; ts=$(_emit_now_ts)
  local out='{"type":"thumb_candidate","ts":'"$ts"
  [[ -n "$run_id" ]]        && out+=',"run_id":"'"$(json_escape "$run_id")"'"'
  out+=',"decision":"'"$(json_escape "$decision")"'"'
  out+=',"path":"'"$(json_escape "$path")"'"'
  [[ -n "$keeper" ]]        && out+=',"keeper":"'"$(json_escape "$keeper")"'"'
  [[ -n "$group_id" ]]      && out+=',"group_id":"'"$(json_escape "$group_id")"'"'
  [[ -n "$width" ]]         && out+=',"width":'"$(_emit_num width "$width")"
  [[ -n "$height" ]]        && out+=',"height":'"$(_emit_num height "$height")"
  [[ -n "$size_bytes" ]]    && out+=',"size_bytes":'"$(_emit_num size_bytes "$size_bytes")"
  [[ -n "$phash_distance" ]] && out+=',"phash_distance":'"$(_emit_num phash_distance "$phash_distance")"
  [[ -n "$reason" ]]        && out+=',"reason":"'"$(json_escape "$reason")"'"'
  out+='}'
  _emit_write "$out"
}

# emit_action_move — file was moved to quarantine (or would be, dry-run).
#   --src VAL       required; source path
#   --dst VAL       required; destination path (quarantine location)
#   --matched VAL   optional; the backup/keeper file that triggered the match
#   --decision VAL  optional; decision label (e.g. thumb_l2_exif)
#   --dry-run BOOL  optional; true|false literal
emit_action_move(){
  $JSON_EVENTS || return 0
  local src="" dst="" matched="" decision="" dry_run="" run_id=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --src)      src="$2";      shift 2 ;;
      --dst)      dst="$2";      shift 2 ;;
      --matched)  matched="$2";  shift 2 ;;
      --decision) decision="$2"; shift 2 ;;
      --dry-run)  dry_run="$2";  shift 2 ;;
      --run-id)   run_id="$2";   shift 2 ;;
      *) echo "emit_action_move: unknown arg $1" >&2; return 0 ;;
    esac
  done
  [[ -z "$run_id" ]] && run_id="${RUN_ID:-}"
  local ts; ts=$(_emit_now_ts)
  local out='{"type":"action","ts":'"$ts"
  [[ -n "$run_id" ]]  && out+=',"run_id":"'"$(json_escape "$run_id")"'"'
  out+=',"kind":"move"'
  out+=',"src":"'"$(json_escape "$src")"'"'
  out+=',"dst":"'"$(json_escape "$dst")"'"'
  [[ -n "$matched" ]]  && out+=',"matched":"'"$(json_escape "$matched")"'"'
  [[ -n "$decision" ]] && out+=',"decision":"'"$(json_escape "$decision")"'"'
  case "$dry_run" in
    true|false) out+=',"dry_run":'"$dry_run" ;;
    "") ;;
    *) echo "emit_action_move: --dry-run must be true|false" >&2 ;;
  esac
  out+='}'
  _emit_write "$out"
}

# emit_action_skip — file was skipped (hardlink, user override, etc.).
#   --src VAL       required; source path
#   --matched VAL   optional; the backup/keeper file that triggered the match
#   --reason VAL    optional; reason code (e.g. hardlink)
#   --decision VAL  optional; decision label
emit_action_skip(){
  $JSON_EVENTS || return 0
  local src="" matched="" reason="" decision="" run_id=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --src)      src="$2";      shift 2 ;;
      --matched)  matched="$2";  shift 2 ;;
      --reason)   reason="$2";   shift 2 ;;
      --decision) decision="$2"; shift 2 ;;
      --run-id)   run_id="$2";   shift 2 ;;
      *) echo "emit_action_skip: unknown arg $1" >&2; return 0 ;;
    esac
  done
  [[ -z "$run_id" ]] && run_id="${RUN_ID:-}"
  local ts; ts=$(_emit_now_ts)
  local out='{"type":"action","ts":'"$ts"
  [[ -n "$run_id" ]]  && out+=',"run_id":"'"$(json_escape "$run_id")"'"'
  out+=',"kind":"skip"'
  out+=',"src":"'"$(json_escape "$src")"'"'
  [[ -n "$matched" ]]  && out+=',"matched":"'"$(json_escape "$matched")"'"'
  [[ -n "$reason" ]]   && out+=',"reason":"'"$(json_escape "$reason")"'"'
  [[ -n "$decision" ]] && out+=',"decision":"'"$(json_escape "$decision")"'"'
  out+='}'
  _emit_write "$out"
}

# emit_action_delete — file was deleted (or would be, dry-run).
#   --src VAL       required; source path
#   --matched VAL   optional; the backup/keeper file that triggered the match
#   --decision VAL  optional; decision label
#   --dry-run BOOL  optional; true|false literal
emit_action_delete(){
  $JSON_EVENTS || return 0
  local src="" matched="" decision="" dry_run="" run_id=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --src)      src="$2";      shift 2 ;;
      --matched)  matched="$2";  shift 2 ;;
      --decision) decision="$2"; shift 2 ;;
      --dry-run)  dry_run="$2";  shift 2 ;;
      --run-id)   run_id="$2";   shift 2 ;;
      *) echo "emit_action_delete: unknown arg $1" >&2; return 0 ;;
    esac
  done
  [[ -z "$run_id" ]] && run_id="${RUN_ID:-}"
  local ts; ts=$(_emit_now_ts)
  local out='{"type":"action","ts":'"$ts"
  [[ -n "$run_id" ]]  && out+=',"run_id":"'"$(json_escape "$run_id")"'"'
  out+=',"kind":"delete"'
  out+=',"src":"'"$(json_escape "$src")"'"'
  [[ -n "$matched" ]]  && out+=',"matched":"'"$(json_escape "$matched")"'"'
  [[ -n "$decision" ]] && out+=',"decision":"'"$(json_escape "$decision")"'"'
  case "$dry_run" in
    true|false) out+=',"dry_run":'"$dry_run" ;;
    "") ;;
    *) echo "emit_action_delete: --dry-run must be true|false" >&2 ;;
  esac
  out+='}'
  _emit_write "$out"
}

# emit_action_restore — file was restored from quarantine (or would be, dry-run).
#   --kind VAL      required; one of: restore | restore_missing | restore_unrecoverable | restore_conflict
#   --src VAL       required; quarantine source path
#   --dst VAL       required; restore destination path
#   --dry-run BOOL  optional; true|false literal
emit_action_restore(){
  $JSON_EVENTS || return 0
  local kind="" src="" dst="" dry_run="" run_id=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --kind)     kind="$2";    shift 2 ;;
      --src)      src="$2";     shift 2 ;;
      --dst)      dst="$2";     shift 2 ;;
      --dry-run)  dry_run="$2"; shift 2 ;;
      --run-id)   run_id="$2";  shift 2 ;;
      *) echo "emit_action_restore: unknown arg $1" >&2; return 0 ;;
    esac
  done
  case "$kind" in
    restore|restore_missing|restore_unrecoverable|restore_conflict) ;;
    *) echo "emit_action_restore: invalid kind '$kind'" >&2; return 0 ;;
  esac
  [[ -z "$run_id" ]] && run_id="${RUN_ID:-}"
  local ts; ts=$(_emit_now_ts)
  local out='{"type":"action","ts":'"$ts"
  [[ -n "$run_id" ]] && out+=',"run_id":"'"$(json_escape "$run_id")"'"'
  out+=',"kind":"'"$(json_escape "$kind")"'"'
  out+=',"src":"'"$(json_escape "$src")"'"'
  out+=',"dst":"'"$(json_escape "$dst")"'"'
  case "$dry_run" in
    true|false) out+=',"dry_run":'"$dry_run" ;;
    "") ;;
    *) echo "emit_action_restore: --dry-run must be true|false" >&2 ;;
  esac
  out+='}'
  _emit_write "$out"
}

# emit_dup_group — a duplicate pair/group was identified.
#   --group-id INT        required; numeric group identifier
#   --match-reason VAL    required; reason code (e.g. md5)
#   --keep-path VAL       required; the file being kept
#   --remove-path VAL     required; the file to be removed (one per event)
emit_dup_group(){
  $JSON_EVENTS || return 0
  local group_id="" match_reason="" keep_path="" remove_path="" run_id=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --group-id)      group_id="$2";      shift 2 ;;
      --match-reason)  match_reason="$2";  shift 2 ;;
      --keep-path)     keep_path="$2";     shift 2 ;;
      --remove-path)   remove_path="$2";   shift 2 ;;
      --run-id)        run_id="$2";        shift 2 ;;
      *) echo "emit_dup_group: unknown arg $1" >&2; return 0 ;;
    esac
  done
  [[ -z "$run_id" ]] && run_id="${RUN_ID:-}"
  local ts; ts=$(_emit_now_ts)
  local out='{"type":"dup_group","ts":'"$ts"
  [[ -n "$run_id" ]] && out+=',"run_id":"'"$(json_escape "$run_id")"'"'
  out+=',"group_id":'"$(_emit_num group_id "$group_id")"
  out+=',"match_reason":"'"$(json_escape "$match_reason")"'"'
  out+=',"keep_path":"'"$(json_escape "$keep_path")"'"'
  out+=',"remove":[{"path":"'"$(json_escape "$remove_path")"'"}]'
  out+='}'
  _emit_write "$out"
}

# emit_progress — progress beacon during a long phase.
#   --phase VAL          enum (scan | hash | phash | apply | restore)
#   --done INT           count of items processed so far
#   --total INT          best-known total
#   --current-path VAL   what's currently being processed
emit_progress(){
  $JSON_EVENTS || return 0
  local phase="" done="" total="" current_path="" run_id=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --phase)         phase="$2"; shift 2 ;;
      --done)          done="$2"; shift 2 ;;
      --total)         total="$2"; shift 2 ;;
      --current-path)  current_path="$2"; shift 2 ;;
      --run-id)        run_id="$2"; shift 2 ;;
      *) echo "emit_progress: unknown arg $1" >&2; return 0 ;;
    esac
  done
  [[ -z "$run_id" ]] && run_id="${RUN_ID:-}"
  local ts; ts=$(_emit_now_ts)
  local out='{"type":"progress","ts":'"$ts"
  [[ -n "$run_id" ]] && out+=',"run_id":"'"$(json_escape "$run_id")"'"'
  out+=',"phase":"'"$(json_escape "$phase")"'"'
  [[ -n "$done" ]]         && out+=',"done":'"$(_emit_num done "$done")"
  [[ -n "$total" ]]        && out+=',"total":'"$(_emit_num total "$total")"
  [[ -n "$current_path" ]] && out+=',"current_path":"'"$(json_escape "$current_path")"'"'
  out+='}'
  _emit_write "$out"
}
